# Generated by Django 3.2.4 on 2021-06-07 13:35

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('division', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('ppe_number', models.CharField(max_length=100)),
                ('osd_number', models.CharField(max_length=100)),
                ('counter_number', models.CharField(max_length=100)),
                ('tariff', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=100)),
                ('osd_next', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('contract_type', models.CharField(max_length=100)),
                ('notice_period', models.CharField(max_length=100)),
                ('contract_duration', models.CharField(max_length=100)),
                ('termination_date', models.CharField(max_length=100)),
                ('sale_start', models.CharField(max_length=100)),
                ('sale_end', models.CharField(max_length=100)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='division.division')),
            ],
        ),
    ]
