# Generated by Django 3.2.4 on 2021-06-20 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0001_initial'),
        ('points', '0002_auto_20210615_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='points.point'),
        ),
        migrations.AlterField(
            model_name='point',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='division.division'),
        ),
    ]
