# Generated by Django 3.2.4 on 2021-06-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_auto_20210620_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='tags',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='tags',
            field=models.ManyToManyField(related_name='points', to='points.Tag'),
        ),
    ]
