# Generated by Django 3.2.6 on 2021-08-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_auto_20210622_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='points', to='points.Tag'),
        ),
    ]
