# Generated by Django 3.2.6 on 2021-08-07 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_alter_point_tags'),
        ('points', '0005_auto_20210804_1413'),
    ]

    operations = [
    ]
