# Generated by Django 3.2.5 on 2021-08-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_merge_0005_alter_point_tags_0005_auto_20210804_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='contract_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='contract_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='counter_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='notice_period',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='osd_next',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='osd_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='power',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='sale_end',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='sale_start',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='seller',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='tariff',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='point',
            name='termination_date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
