# Generated by Django 3.2.6 on 2021-09-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0007_auto_20210809_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='point',
            options={'verbose_name': 'punkt', 'verbose_name_plural': 'punkty'},
        ),
        migrations.RemoveField(
            model_name='point',
            name='address',
        ),
        migrations.AddField(
            model_name='point',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='miasto'),
        ),
        migrations.AddField(
            model_name='point',
            name='post',
            field=models.CharField(blank=True, max_length=10, verbose_name='poczta'),
        ),
        migrations.AddField(
            model_name='point',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='ulica'),
        ),
        migrations.AddField(
            model_name='point',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='nr'),
        ),
        migrations.AddField(
            model_name='point',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nazwa'),
        ),
    ]
