# Generated by Django 3.2.7 on 2021-09-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0004_auto_20210926_1940'),
        ('points', '0008_auto_20210905_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'komentarz', 'verbose_name_plural': 'komentarze'},
        ),
        migrations.AlterModelOptions(
            name='pointcost',
            options={'verbose_name': 'koszt', 'verbose_name_plural': 'koszty'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tagi'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='points.point', verbose_name='dywyzja'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='treść'),
        ),
        migrations.AlterField(
            model_name='point',
            name='contract_duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='okres obowiązywania umowy'),
        ),
        migrations.AlterField(
            model_name='point',
            name='contract_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='typ umowy'),
        ),
        migrations.AlterField(
            model_name='point',
            name='counter_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='numer licznika'),
        ),
        migrations.AlterField(
            model_name='point',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='division.division', verbose_name='dywizja'),
        ),
        migrations.AlterField(
            model_name='point',
            name='notice_period',
            field=models.CharField(blank=True, max_length=100, verbose_name='okres wypowedzenia'),
        ),
        migrations.AlterField(
            model_name='point',
            name='osd_next',
            field=models.CharField(blank=True, max_length=100, verbose_name='nazwa lokalnego OSD'),
        ),
        migrations.AlterField(
            model_name='point',
            name='osd_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='numer OSD'),
        ),
        migrations.AlterField(
            model_name='point',
            name='post',
            field=models.CharField(blank=True, max_length=100, verbose_name='poczta'),
        ),
        migrations.AlterField(
            model_name='point',
            name='power',
            field=models.CharField(blank=True, max_length=100, verbose_name='moc umowna'),
        ),
        migrations.AlterField(
            model_name='point',
            name='ppe_number',
            field=models.CharField(max_length=100, verbose_name='numer PPE'),
        ),
        migrations.AlterField(
            model_name='point',
            name='sale_end',
            field=models.CharField(blank=True, max_length=100, verbose_name='zakończenie sprzedaży'),
        ),
        migrations.AlterField(
            model_name='point',
            name='sale_start',
            field=models.CharField(blank=True, max_length=100, verbose_name='rozpoczęcie sprzedaży'),
        ),
        migrations.AlterField(
            model_name='point',
            name='seller',
            field=models.CharField(blank=True, max_length=100, verbose_name='sprzedawca'),
        ),
        migrations.AlterField(
            model_name='point',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='points', to='points.Tag', verbose_name='tagi'),
        ),
        migrations.AlterField(
            model_name='point',
            name='tariff',
            field=models.CharField(blank=True, max_length=100, verbose_name='taryfa'),
        ),
        migrations.AlterField(
            model_name='point',
            name='termination_date',
            field=models.CharField(blank=True, max_length=100, verbose_name='data zakończenia umowy'),
        ),
        migrations.AlterField(
            model_name='point',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='zweryfikowany'),
        ),
        migrations.AlterField(
            model_name='pointcost',
            name='costs',
            field=models.FloatField(verbose_name='koszty'),
        ),
        migrations.AlterField(
            model_name='pointcost',
            name='date',
            field=models.DateField(verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='pointcost',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='points.point', verbose_name='punkt'),
        ),
        migrations.AlterField(
            model_name='pointcost',
            name='usage',
            field=models.IntegerField(verbose_name='zużycie'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='nazwa'),
        ),
    ]
