# Generated by Django 4.1.7 on 2023-03-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0009_auto_20210926_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='point',
            name='ppe_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='numer PPE'),
        ),
    ]
