# Generated by Django 4.1.7 on 2023-04-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0010_alter_point_name_alter_point_ppe_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='seller_change',
            field=models.CharField(blank=True, max_length=100, verbose_name='pierwsza / kolejna zmiana sprzedawcy'),
        ),
        migrations.AlterField(
            model_name='point',
            name='sale_end',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='zakończenie sprzedaży'),
        ),
        migrations.AlterField(
            model_name='point',
            name='sale_start',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='rozpoczęcie sprzedaży'),
        ),
        migrations.AlterField(
            model_name='point',
            name='termination_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='data zakończenia umowy'),
        ),
    ]
