# Generated by Django 4.1.7 on 2023-04-07 21:42
from datetime import datetime

from django.db import migrations, models


def set_proper_date(apps, field):
    point_model = apps.get_model('points', 'Point')
    for point in point_model.objects.all():
        try:
            date = getattr(point, field)
            new_date = datetime.strptime(date, '%d.%m.%Y').strftime('%Y-%m-%d')
            setattr(point, field, new_date)
            point.save()
        except (AttributeError, ValueError):
            setattr(point, field, None)
            point.save()


def set_sale_end(apps, schema_editor):
    set_proper_date(apps, 'sale_end')


def set_sale_start(apps, schema_editor):
    set_proper_date(apps, 'sale_start')


def set_termination_date(apps, schema_editor):
    set_proper_date(apps, 'termination_date')


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0011_alter_point_sale_end_alter_point_sale_start_and_more'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE points_point DISABLE TRIGGER ALL'),
        migrations.RunPython(set_sale_end),
        migrations.AlterField(
            model_name='point',
            name='sale_end',
            field=models.DateField(null=True, blank=True, verbose_name='zakończenie sprzedaży'),
        ),
        migrations.RunPython(set_sale_start),
        migrations.AlterField(
            model_name='point',
            name='sale_start',
            field=models.DateField(null=True, blank=True, verbose_name='rozpoczęcie sprzedaży'),
        ),
        migrations.RunPython(set_termination_date),
        migrations.AlterField(
            model_name='point',
            name='termination_date',
            field=models.DateField(null=True, blank=True, verbose_name='data zakończenia umowy'),
        ),
        migrations.RunSQL('ALTER TABLE points_point ENABLE TRIGGER ALL'),
    ]
