# Generated by Django 4.1.8 on 2023-04-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0008_division_address_division_company_address_and_more'),
        ('points', '0012_alter_point_sale_end_alter_point_sale_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='division.division', verbose_name='jednostka'),
        ),
    ]
