# Generated by Django 4.1.9 on 2023-05-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0013_alter_point_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='street_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='nr'),
        ),
        migrations.AlterField(
            model_name='point',
            name='zip_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='kod pocztowy'),
        ),
    ]
