# Generated by Django 4.1.11 on 2023-09-18 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0014_alter_point_street_number_alter_point_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointcost',
            name='costs',
        ),
        migrations.AddField(
            model_name='pointcost',
            name='billing_cycle',
            field=models.CharField(default='', max_length=100, verbose_name='Cykl rozliczeniowy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='brutto',
            field=models.FloatField(default=0, verbose_name='Wartość brutto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='fv_number',
            field=models.CharField(default='', max_length=100, verbose_name='Numer FV'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='netto',
            field=models.FloatField(default=0, verbose_name='Wartość netto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='nip',
            field=models.CharField(default='', max_length=100, verbose_name='NIP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='osd',
            field=models.CharField(default='', max_length=100, verbose_name='OSD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='payer_address_city',
            field=models.CharField(default='', max_length=100, verbose_name='Adres płatnika - miasto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='payer_address_street',
            field=models.CharField(default='', max_length=100, verbose_name='Adres płatnika - ulica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='payer_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nazwa płatnika'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='payer_number',
            field=models.CharField(default='', max_length=100, verbose_name='Nr płatnika'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='ppe_number',
            field=models.CharField(default='', max_length=100, verbose_name='Numer PPE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='previous_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 16, 0, 10, 538764, tzinfo=datetime.timezone.utc), verbose_name='Data poprzedniego odczytu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='read_month',
            field=models.IntegerField(default=0, verbose_name='Miesiąc odczytu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='receiver_address_city',
            field=models.CharField(default='', max_length=100, verbose_name='Adres odbiorcy - miasto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='receiver_address_street',
            field=models.CharField(default='', max_length=100, verbose_name='Adres odbiorcy - ulica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='receiver_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nazwa odbiorcy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='tariff',
            field=models.CharField(default='', max_length=100, verbose_name='Taryfa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='trading_value',
            field=models.FloatField(default=0, verbose_name='Wartość obrotu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointcost',
            name='vat',
            field=models.FloatField(default=0, verbose_name='VAT'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointcost',
            name='date',
            field=models.DateField(verbose_name='Data bieżącego odczytu'),
        ),
        migrations.AlterField(
            model_name='pointcost',
            name='usage',
            field=models.IntegerField(verbose_name='Ilość energii'),
        ),
    ]
