# Generated by Django 4.1.11 on 2023-09-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0015_remove_pointcost_costs_pointcost_billing_cycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointcost',
            name='ppe_number',
        ),
    ]
