# Generated by Django 4.1.11 on 2023-09-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0016_remove_pointcost_ppe_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointcost',
            name='related_entity',
            field=models.CharField(default='', max_length=100, verbose_name='Powiązana jednostka'),
            preserve_default=False,
        ),
    ]
