# Generated by Django 4.1.13 on 2023-12-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0017_pointcost_related_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointProxy',
            fields=[
            ],
            options={
                'verbose_name': 'zużycie',
                'verbose_name_plural': 'zużycie',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('points.point',),
        ),
        migrations.AddField(
            model_name='point',
            name='annual_consumption',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Zużycie roczne'),
        ),
    ]
