# Generated by Django 3.2.7 on 2021-09-26 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('division', '0003_alter_division_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'dywizja', 'verbose_name_plural': 'dywizje'},
        ),
        migrations.AlterField(
            model_name='division',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nazwa'),
        ),
    ]
