# Generated by Django 3.2.12 on 2022-03-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0004_auto_20210926_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazwa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('divisions', models.ManyToManyField(to='division.Division', verbose_name='dywizje')),
            ],
            options={
                'verbose_name': 'grupa zakupowa',
                'verbose_name_plural': 'grupy zakupowe',
            },
        ),
    ]
