# Generated by Django 4.1.7 on 2023-03-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0005_buyinggroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyinggroup',
            name='divisions',
            field=models.ManyToManyField(related_name='buying_groups', to='division.division', verbose_name='dywizje'),
        ),
    ]
