# Generated by Django 4.1.8 on 2023-04-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0006_alter_buyinggroup_divisions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'Jednostka', 'verbose_name_plural': 'Jednostki'},
        ),
        migrations.AlterField(
            model_name='buyinggroup',
            name='divisions',
            field=models.ManyToManyField(related_name='buying_groups', to='division.division', verbose_name='jednostki'),
        ),
    ]
