# Generated by Django 4.1.7 on 2023-04-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0007_alter_division_options_alter_buyinggroup_divisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='adres nabywcy'),
        ),
        migrations.AddField(
            model_name='division',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='adres do faktury'),
        ),
        migrations.AddField(
            model_name='division',
            name='nip',
            field=models.CharField(blank=True, max_length=13, verbose_name='NIP'),
        ),
        migrations.AddField(
            model_name='division',
            name='receiver',
            field=models.CharField(blank=True, max_length=100, verbose_name='odbiorca'),
        ),
    ]
