# Generated by Django 4.1.7 on 2023-08-19 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('division', '0008_division_address_division_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik'),
        ),
    ]
